import "./globals.css";
import { Palanquin_Dark, Orienta } from "next/font/google";
import { SessionProvider } from 'next-auth/react';
import Header from "@/components/Header";
import Footer from "@/components/Footer";

// Fonts
const palanquinDark = Palanquin_Dark({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-palanquin-dark",
});
const orienta = Orienta({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-orienta",
});

export const metadata = {
  title: "My Next.js App",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${palanquinDark.variable} ${orienta.variable}`}
    >
      <body className="font-orienta">
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
